# Generated by Django 2.1.7 on 2019-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190215_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
