# Generated by Django 2.1.7 on 2019-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_access_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
