# Generated by Django 2.1.7 on 2019-02-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190218_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_challenge',
        ),
        migrations.AddField(
            model_name='post',
            name='access_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
