# Generated by Django 2.1.7 on 2019-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190222_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_challenge',
        ),
        migrations.AddField(
            model_name='country',
            name='access_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
