# Generated by Django 2.1.7 on 2019-03-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_country_access_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='access_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
